# Generated by Django 3.2.2 on 2021-08-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('parent_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher_allocated', models.CharField(blank=True, max_length=50, null=True)),
                ('current_teacher', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_manager', models.CharField(blank=True, max_length=50, null=True)),
                ('lsq_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_active_date', models.DateTimeField(blank=True, null=True)),
                ('ptm_status', models.BooleanField(default=False)),
                ('last_ptm_date', models.DateTimeField(blank=True, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sessions_credited', models.CharField(blank=True, max_length=100, null=True)),
                ('allowed_total_classes', models.IntegerField(default=0)),
                ('taken_total_classes', models.IntegerField(default=0)),
                ('remaining_classes', models.IntegerField(default=-1)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('timestamp', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.IntegerField()),
                ('fname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('age', models.IntegerField()),
                ('status', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees', models.FloatField(default=0.0)),
                ('fees_paid', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('sessions_credited', models.CharField(blank=True, max_length=100, null=True)),
                ('latest_payment_date', models.DateTimeField(blank=True, null=True)),
                ('balance_fee_follow_date', models.DateTimeField(blank=True, null=True)),
                ('renewal1_date', models.DateTimeField(blank=True, null=True)),
                ('renewal2_date', models.DateTimeField(blank=True, null=True)),
                ('renewal_status', models.BooleanField(default=False)),
                ('payment_pending', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('child_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projectApp.child')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='learning_objective',
            field=models.ManyToManyField(to='projectApp.LearningObjective'),
        ),
    ]
